# Generated by Django 3.1.7 on 2021-02-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20210224_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2_emission',
            name='measured_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='heatrate',
            name='measured_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nox_emission',
            name='measured_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='so2_emission',
            name='measured_date',
            field=models.DateField(),
        ),
    ]
