# Generated by Django 3.1.7 on 2021-02-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20210221_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2_emission',
            name='emission_Mt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nox_emission',
            name='emission_Mt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='so2_emission',
            name='emission_Mt',
            field=models.FloatField(),
        ),
    ]
