# Generated by Django 3.1.7 on 2021-02-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20210224_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co2_Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_store', models.PositiveBigIntegerField()),
                ('measured_date', models.DateField()),
            ],
        ),
    ]
