# Generated by Django 3.1.7 on 2021-02-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_co2_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2_reserve',
            name='measured_at_minute',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
